"""merged profile with user

Revision ID: 4e985c9bdba6
Revises: a1885cb4d37d
Create Date: 2024-08-27 06:33:33.125654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e985c9bdba6'
down_revision = 'a1885cb4d37d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('birth_date')

    # ### end Alembic commands ###
