"""merged profile with user

Revision ID: a1885cb4d37d
Revises: d7a384a0897e
Create Date: 2024-08-27 06:29:32.391329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1885cb4d37d'
down_revision = 'd7a384a0897e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profiles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('phonenumber', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('profile_image', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('about', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('about')
        batch_op.drop_column('profile_image')
        batch_op.drop_column('phonenumber')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    op.create_table('profiles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('phonenumber', sa.VARCHAR(length=20), nullable=True),
    sa.Column('profile_image', sa.VARCHAR(length=128), nullable=True),
    sa.Column('about', sa.TEXT(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###
